config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'hello#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
         end
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
  
  def link
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          tag_tweets = Tag.find_by(name: key).tweets
          @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
        end
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def okawa
    
  end

  
  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body,:image, tag_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekRails7Win</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
Enjoy programming!
<%= link_to "新規投稿",new_tweet_path %>
<h1>GeekTwitter</h1>

<h3>投稿を検索</h3>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
<% end %>


<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>Tweet一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>


<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.user.email %>
      <%= t.body %>
      <% if t.image.attached? %>
        <%= image_tag t.image, size: '250x200'%>
      <% end %>
      <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                  <p>いいねを取り消す</p><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                  <p>いいね</p><%= t.likes.count %>
              <% end %>
          <% end %>
      <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
      <% end %>
      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
<% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>

  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@tweet) %>
      <%= button_to tweet_like_path(@tweet), method: :delete do %>
        <p>いいねを取り消す</p><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= button_to tweet_likes_path(@tweet), method: :post do %>
        <p>いいね</p><%= @tweet.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <p>いいねの数 = </p><%= @tweet.likes.count %>
  <% end %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>


app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>